[package]
name = "surreal"
description = "The Surreal game engine"
authors.workspace = true
edition.workspace = true
version.workspace = true

[workspace.package]
authors = ["Matt Kleinschafer <xeusalmighty@gmail.com>"]
edition = "2021"
version = "0.1.0"

[workspace]
members = ["backends/*", "common", "macros", "modules/*"]

[profile.dev.package."*"]
opt-level = 3

[features]
default = ["macros", "audio", "graphics", "input", "physics"]

[dependencies]
# core
common = { package = "surreal-common", path = "./common" }
macros = { package = "surreal-macros", path = "./macros", optional = true }

# backends
sdl = { package = "surreal-sdl", path = "./backends/sdl", optional = true }
gba = { package = "surreal-gba", path = "./backends/gba", optional = true }

# modules
assets = { package = "surreal-assets", path = "./modules/assets", optional = true }
audio = { package = "surreal-audio", path = "./modules/audio", optional = true }
graphics = { package = "surreal-graphics", path = "./modules/graphics", optional = true }
input = { package = "surreal-input", path = "./modules/input", optional = true }
physics = { package = "surreal-physics", path = "./modules/physics", optional = true }
scene = { package = "surreal-scene", path = "./modules/scene", optional = true }
ui = { package = "surreal-ui", path = "./modules/ui", optional = true }
