[package]
name = "surreal"
description = "The Surreal game engine"
authors.workspace = true
edition.workspace = true
version.workspace = true

[workspace.package]
authors = ["Matt Kleinschafer <xeusalmighty@gmail.com>"]
edition = "2021"
version = "0.1.0"

[workspace]
members = ["backends/*", "common", "editor", "macros", "modules/*"]

[profile.dev.package."*"]
opt-level = 3

[features]
default = []

[workspace.dependencies]
# shared dependencies
serde = { version = "1.0.159", features = ["derive"] }
bitflags = "2.1.0"

[dependencies]
# core
common = { package = "surreal-common", path = "./common" }
editor = { package = "surreal-editor", path = "./editor", optional = true }

# backends
sdl = { package = "surreal-backend-sdl", path = "./backends/sdl", optional = true }

# modules
assets = { package = "surreal-assets", path = "./modules/assets", optional = true }
audio = { package = "surreal-audio", path = "./modules/audio", optional = true }
graphics = { package = "surreal-graphics", path = "./modules/graphics", optional = true }
input = { package = "surreal-input", path = "./modules/input", optional = true }
physics = { package = "surreal-physics", path = "./modules/physics", optional = true }
scripting = { package = "surreal-scripting", path = "./modules/scripting", optional = true }

[[example]]
name = "hello-world"
required-features = ["sdl", "graphics", "input"]

[[example]]
name = "falling-sand"
required-features = ["sdl", "graphics", "input"]
