[package]
name = "surreal"
description = "The Surreal game engine"
version = "0.1.0"
authors = ["Matt Kleinschafer <xeusalmighty@gmail.com>"]
edition = "2021"

[workspace]
members = ["macros"]

[profile.dev.package."*"]
opt-level = 3 # compile third party dependencies by default with some sane optimizations

[features]
default = ["prototype"]
profiling = ["profiling/profile-with-optick"]
prototype = []

[dependencies]
# internal dependencies
surreal-macros = { path = "macros" }

# core dependencies
anyhow = "1.0.57"
ab_glyph = "0.2.15"
image = { version = "0.24.1", default-features = false, features = ["jpeg", "png", "ico"] }
egui = { version = "0.18.1" }
profiling = { version = "1.0.6" }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
lazy_static = "1.4.0"
log = "0.4.17"

# platform dependencies
gl = "0.14.0"
glutin = { version = "0.28.0", default-features = false, features = [ "x11" ] }

