[package]
name = "surreal"
description = "The Surreal game engine"
version = "0.1.0"
authors = ["Matt Kleinschafer <xeusalmighty@gmail.com>"]
edition = "2021"

[workspace]
members = ["macros"]

[profile.dev.package."*"]
opt-level = 3 # compile third party dependencies by default with some sane optimizations

[features]
default = ["desktop", "headless", "prototype", "scripting-lua", "profile-with-optick"]
desktop = []
headless = []
prototype = []
scripting-lua = ["mlua"]
profile-with-optick = ["profiling/profile-with-optick"]
profile-with-puffin = ["profiling/profile-with-puffin", "puffin_egui"]

[dependencies]
# internal dependencies
surreal-macros = { path = "macros" }

# core dependencies
anyhow = "1.0.57"
image = { version = "0.24.1", default-features = false, features = ["jpeg", "png", "ico"] }
profiling = { version = "1.0.6" }
egui = { version = "0.18.1" }
puffin_egui = { version = "0.15.0", optional = true }

# serialization/deserialization
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
ron = "0.7"

# platform dependencies
gl = "0.14.0"
raw-gl-context = "0.1.2"
winit = { version = "0.22.2", default-features = false }

# scripting dependencies
mlua = { version = "0.7.4", features = ["lua54", "vendored"], optional = true }
