[package]
name = "surreal"
version = "0.1.0"
authors = ["Matt Kleinschafer <matt.kleinschafer@xero.com>"]
edition = "2018"

[profile.dev.package."*"]
opt-level = 2

[profile.release.build-override]
opt-level = 0

[dependencies]
cgmath = "0.17.0"
enumflags2 = "0.6.4"
enumflags2_derive = "0.6.4"
gl = "0.14.0"
image = { version = "0.22.1", default-features = false, features = ["png_codec", "jpeg"] }
rand = { version = "0.6.5", default-features = false, features = ["std"] }
rlua = { version = "0.17.0", optional = true }
rspirv = { version = "0.6.0", optional = true }
sdl2 = { version = "0.34.1", features = ["bundled"] }
smallvec = "1.4.0"

[features]
default = []
kismet = []
lua = ["rlua"]
shady = ["rspirv"]
