[package]
name = "surreal"
version = "0.1.0"
authors = ["Matt Kleinschafer <matt.kleinschafer@xero.com>"]
edition = "2018"

[profile.dev.package."*"]
opt-level = 2

[profile.release.build-override]
opt-level = 0

[dependencies]
# platform
luminance = "0.39.0"
luminance-glfw = "0.12.2"
luminance-derive = "0.5.3"

# utilities
cgmath = "0.17.0"
enumflags2 = "0.6.4"
enumflags2_derive = "0.6.4"
image = { version = "0.22.1", default-features = false, features = ["png_codec"] }
log = "0.4.8"
num-traits = "0.2.12"
rand = { version = "0.6.5", default-features = false, features = ["std"] }
rlua = "0.17.0"
smallvec = "1.4.0"
