[package]
name = "surreal"
version = "0.1.0"
authors = ["Matt Kleinschafer <matt.kleinschafer@xero.com>"]
edition = "2018"

[features]
default = ["opengl"]
opengl = []
editor = []

[dependencies]
chrono = "0.4.7"
enumflags2 = "^0.5"
enumflags2_derive = "^0.5"
gl = "0.10.0"
glam = "0.7.1"
hotwatch = "0.4.2"
image = "0.22.1"
imgui = "0.1.0"
imgui-opengl-renderer = "0.5"
imgui-sdl2 = "0.6.0"
log = "0.4.8"
num-traits = "0.2.4"
rand = "0.6.5"
rlua = "0.16.3"

[dependencies.sdl2]
version = "0.32.2"
features = ["bundled"]