[package]
name = "surreal"
version = "0.1.0"
authors = ["Matt Kleinschafer <xeusalmighty@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "examples/hello-world",
]

[dependencies]
cgmath = "0.17.0"
enumflags2 = "0.6.4"
gl = "0.14.0"
glutin = { version = "0.25.1", default-features = false }
image = { version = "0.23.11", default-features = false, features = ["png"] }
rand = { version = "0.7.3", default-features = false, features = ["std"] }
rodio = { version = "0.13.0", default-features = false }
rspirv = { version = "0.7", optional = true }
smallvec = "1.4.2"

[features]
default = []
desktop = ["glutin/x11"]
shady = ["rspirv"]
