[package]
name = "surreal"
description = "The Surreal game engine"
version = "0.1.0"
authors = ["Matt Kleinschafer <xeusalmighty@gmail.com>"]
edition = "2021"

[workspace]
members = ["macros"]

[profile.dev.package."*"]
opt-level = 3 # compile third party dependencies by default with some sane optimizations

[features]
default = ["prototype"]
profiling = ["profiling/profile-with-optick"]
prototype = []

[dependencies]
# internal dependencies
surreal-macros = { path = "macros" }

# core dependencies
anyhow = "1"
ab_glyph = "0.2"
chrono = "0.4"
image = { version = "0.24", default-features = false, features = ["jpeg", "png", "ico"] }
egui = { version = "0.18" }
profiling = { version = "1" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
smallvec = "1.8"
lazy_static = "1"
log = "0.4"

# platform dependencies
gl = "0.14"
oal-sys = "0.0.2"
glutin = { version = "0.28", default-features = false, features = [ "x11" ] }

