[package]
name = "surreal"
version = "0.1.0"
authors = ["Matt Kleinschafer <xeusalmighty@gmail.com>"]
edition = "2018"

[workspace]
members = [
    "examples/hello-world",
]

[dependencies]
cgmath = "0.17.0"
enumflags2 = "0.6.4"
enumflags2_derive = "0.6.4"
futures = "0.3.7"
gl = "0.14.0"
glutin = { version = "0.25.1", default-features = false }
image = { version = "0.23.11", default-features = false, features = ["png"] }
rand = { version = "0.7.3", default-features = false, features = ["std"] }
winit = { version = "0.23", optional = true }
smallvec = "1.4.2"
rspirv = { version = "0.7", optional = true }

[features]
default = []
desktop = ["winit"]
shady = ["rspirv"]
