[package]
name = "surreal"
version = "0.1.0"
authors = ["Matt Kleinschafer <matt.kleinschafer@xero.com>"]
edition = "2018"

[features]
default = []

[dependencies]
log = "0.4.8"
num-traits = "0.2.12"
smallvec = "1.4.0"
cgmath = "0.17.0"
rand = { version = "0.6.5", default-features=false }
image = { version="0.22.1", default-features=false, features=["png_codec", "jpeg"] }
