[package]
name = "surreal"
description = "The Surreal game engine"
version = "0.1.0"
authors = ["Matt Kleinschafer <xeusalmighty@gmail.com>"]
edition = "2021"

[workspace]
members = [ "macros" ]

[profile.dev.package."*"]
opt-level = 3 # compile third party dependencies by default with some sane optimizations

[features]
default = ["desktop", "headless", "prototype"]
desktop = []
headless = []
prototype = []

[dependencies]
# internal dependencies
surreal-macros = { path = "macros" }

# third-party dependencies
anyhow = "1.0.57"
gl = "0.14.0"
raw-gl-context = "0.1.2"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
image = { version = "0.24.1", default-features = false, features = ["jpeg", "png", "ico"] }
winit = { version = "0.22.2", default-features = false }
