[package]
name = "surreal"
version = "0.1.0"
authors = ["Matt Kleinschafer <matt.kleinschafer@xero.com>"]
edition = "2018"

[features]
default = []
editor = []

[dependencies]
rlua = "0.16.3"
specs = "0.15.0"
rand = "0.7.0"

[dependencies.sdl2]
version = "0.32.2"
features = ["bundled"]

[dependencies.glam]
version = "0.7.1"
default-features = false