[package]
name = "surreal"
version = "0.1.0"
authors = ["Matt Kleinschafer <matt.kleinschafer@xero.com>"]
edition = "2018"

[profile.dev.package."*"]
opt-level = 2

[profile.release.build-override]
opt-level = 0

[features]
default = ["editor", "graphics", "scripting", "platform"]
editor = []
graphics = []
scripting = []
platform = ["luminance", "luminance-glfw", "luminance-derive"]

[dependencies]
# platform
luminance = { version = "0.39.0", optional = true }
luminance-glfw = { version = "0.12.2", optional = true }
luminance-derive = { version = "0.5.3", optional = true }

# utilities
log = "0.4.8"
num-traits = "0.2.12"
smallvec = "1.4.0"
enumflags2 = "0.6.4"
enumflags2_derive = "0.6.4"
euclid = "0.20.13"
rand = { version = "0.6.5", default-features = false, features = ["std"] }
image = { version = "0.22.1", default-features = false, features = ["png_codec", "jpeg"] }

