[package]
name = "surreal"
description = "The Surreal game engine"
version = "0.1.0"
authors = ["Matt Kleinschafer <xeusalmighty@gmail.com>"]
edition = "2021"

[workspace]
members = [
    "core",
    "editor",
    "macros",
    "modules/*",
    "scenes/*",
    "servers/*",
    "tools/*"
]

[features]
default = ["audio", "graphics", "input", "physics"]
profiling = ["core/profiling"]
hdrp = ["graphics/hdrp"]
lwrp = ["graphics/lwrp"]

[dependencies]
# core
core = { package = "surreal-core", path = "./core" }
editor = { package = "surreal-editor", path = "./editor", optional = true }
macros = { package = "surreal-macros", path = "./macros", optional = true }

# modules
ai = { package = "surreal-modules-ai", path = "./modules/ai", optional = true }
animation = { package = "surreal-modules-animation", path = "./modules/animation", optional = true }
csg = { package = "surreal-modules-csg", path = "./modules/csg", optional = true }
scripting = { package = "surreal-modules-scripting", path = "modules/scripting", optional = true }
prototype = { package = "surreal-modules-prototype", path = "./modules/prototype", optional = true }
streaming = { package = "surreal-modules-streaming", path = "./modules/streaming", optional = true }
voxels = { package = "surreal-modules-voxels", path = "./modules/voxels", optional = true }

# scenes
scene2d = { package = "surreal-scene-2d", path = "./scenes/2d", optional = true }
scene3d = { package = "surreal-scene-3d", path = "./scenes/3d", optional = true }

# servers
audio = { package = "surreal-server-audio", path = "./servers/audio", optional = true }
graphics = { package = "surreal-server-graphics", path = "./servers/graphics", optional = true }
input = { package = "surreal-server-input", path = "./servers/input", optional = true }
physics = { package = "surreal-server-physics", path = "./servers/physics", optional = true }

[dev-dependencies]
egui = "0.20.1" # for examples

[[example]]
name = "bunnymark"
required-features = ["prototype"]

[[example]]
name = "egui"
required-features = ["prototype"]

[[example]]
name = "fonts"
required-features = ["prototype"]

[[example]]
name = "hello-world"
required-features = ["prototype"]

[[example]]
name = "sand"
required-features = ["prototype"]

[[example]]
name = "tilemaps"
required-features = ["prototype"]