[package]
name = "surreal"
version = "0.1.0"
authors = ["Matt Kleinschafer <xeusalmighty@gmail.com>"]
edition = "2021"

[workspace]
members = [
    "examples/falling-sand",
    "examples/hello-world"
]

[dependencies]
anyhow = "1.0.44"
gl = "0.14.0"
raw-gl-context = "0.1.2"
winit = { version = "0.22.2", default-features = false }

[features]
default = ["desktop"]
desktop = []
