[package]
name = "surreal"
description = "The Surreal game engine"
version = "0.1.0"
authors = ["Matt Kleinschafer <xeusalmighty@gmail.com>"]
edition = "2021"

[workspace]
members = ["core", "drivers/*", "editor", "platform/*", "modules/*", "tools/*"]

[features]
default = ["editor", "prototype", "profiling"]

# core features
profiling = ["surreal-core/profiling"]
editor = ["surreal-editor"]

# module features
csg = ["surreal-modules-csg"]
gdscript = ["surreal-modules-gdscript"]
prototype = ["surreal-modules-prototype"]
voxels = ["surreal-modules-voxels"]

[dependencies]
surreal-core = { path = "./core" }
surreal-editor = { path = "./editor", optional = true }
surreal-modules-csg = { path = "./modules/csg", optional = true }
surreal-modules-gdscript = { path = "./modules/gdscript", optional = true }
surreal-modules-prototype = { path = "./modules/prototype", optional = true }
surreal-modules-voxels = { path = "./modules/voxels", optional = true }

[dev-dependencies]
egui = "0.20.1" # for examples