edition = "2021"
tab_spaces = 2
max_width = 140
hard_tabs = false
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = false
force_explicit_abi = true
normalize_comments = true
normalize_doc_attributes = true
