edition = "2021"
tab_spaces = 2
max_width = 120
wrap_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
where_single_line = true
normalize_comments = true
overflow_delimited_expr = true
