[package]
name = "surreal-visualshader"
version = "0.1.0"
edition = "2021"

[dependencies]
surreal = { package = "surreal-core", path = "../../core" }
graphics =  { package = "surreal-graphics", path = "../../servers/graphics" }