[package]
name = "flappy-bird"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
surreal = { path = "../../", features = ["graphics", "input", "sdl"] }
hecs = "0.10.4"