[package]
name = "surreal-graphics"
version = "0.1.0"
edition = "2021"

[features]
default = ["opengl", "vulkan"]
hdrp = []
lwrp = []
opengl = ["gl"]
vulkan = ["ash", "ash-window"]

[dependencies]
surreal = { package = "surreal-core", path = "../../core" }
gl = { version = "0.14", optional = true }
ash = { version = "0.37.1+1.3.235", optional = true }
ash-window = { version = "0.12.0", optional = true }
raw-window-handle = "0.5.0"

[dev-dependencies]
winit = "0.27.5"
