[package]
name = "falling-sand"
version = "0.1.0"
authors = ["Matt Kleinschafer <xeusalmighty@gmail.com>"]
edition = "2018"

[features]
default = []

[dependencies]
surreal = { version = "*", path = "../../" }
pixels = "0.2.0"
winit = "0.22.0"
