[package]
name = "isaac"
description = "A remake of the classic 'Binding of Isaac' in Rust using Surreal"
version = "0.1.0"
edition = "2021"

[dependencies]
surreal = { version = "*", path = "../..", features = ["desktop"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"