[package]
name = "hello-world"
version = "0.1.0"
authors = ["Matt Kleinschafer <xeusalmighty@gmail.com>"]
edition = "2018"

[dependencies]
surreal = { version = "*", path = "../../", features=["desktop"] }