[package]
name = "surreal-audio"
description = "Surreal audio engine"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
core = { package = "surreal-core", path = "../../core" }
thiserror = "1.0.26"
