[package]
name = "surreal-audio"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
surreal = { package = "surreal-core", path = "../../core" }
thiserror = "1.0.26"
