[package]
name = "surreal-scripting-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
surreal = { package = "surreal-core", path = "../../core" }
scripting = { package = "surreal-scripting", path = "../scripting" }
tower = "0.4.13"