[package]
name = "surreal-graphics"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
surreal = { package = "surreal-core", path = "../../core" }
serde = { version = "1.0.159", features = ["derive"] }
thiserror = "1.0.26"

# platform dependencies
gl = "0.14.0"
glutin = "0.30.3"
