[package]
name = "surreal-modules-csg"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { package = "surreal-core", path = "../../core" }
macros = { package = "surreal-macros", path = "../../macros" }