[package]
name = "surreal-core"
version = "0.1.0"
edition = "2021"

[features]
profiling = ["profiling/profile-with-optick"]

[dependencies]
# core dependencies
anyhow = "1.0.66"
ab_glyph = "0.2"
bitflags = "1.3"
chrono = "0.4"
image = { version = "0.24", default-features = false, features = ["jpeg", "png", "ico"] }
egui = "0.20.1"
profiling = "1.0.7"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
serde_yaml = "0.9"
smallvec = "1.8"
lazy_static = "1.4.0"
log = "0.4"
uuid = { version = "1.2.2", features = ["serde"] }

# platform dependencies
gl = "0.14"
oal-sys = "0.0.2"
glutin = { version = "0.28.0", default-features = false, features = [ "x11" ] }