[package]
name = "surreal-core"
version = "0.1.0"
edition = "2021"

[features]
default = ["json", "ron", "toml", "yaml"]
profiling = [] # TODO: get optick compilation working in actions

[dependencies]
# core dependencies
anyhow = "1.0.66"
ab_glyph = "0.2"
bitflags = "1.3"
chrono = "0.4"
image = { version = "0.24", default-features = false, features = ["jpeg", "png", "ico"] }
egui = "0.20.1"
glam = { version = "0.22.0", features = ["serde"] }
profiling = "1.0.7"
smallvec = "1.8"
lazy_static = "1.4.0"
log = "0.4"
uuid = { version = "1.2.2", features = ["serde"] }

# serde and friends
serde = { version = "1.0.152", features = ["derive"] }
json = { package = "serde_json", version = "1.0.91", optional = true }
ron = { version = "0.8.0", optional = true }
toml = { version = "0.5.10", optional = true }
yaml = { package = "serde_yaml", version = "0.9", optional = true }

# platform dependencies
gl = "0.14"
oal-sys = "0.0.2"
glutin = { version = "0.28.0", default-features = false, features = ["x11"] }