[package]
name = "surreal-scripting"
version = "0.1.0"
edition = "2021"

[dependencies]
surreal = { package = "surreal-core", path = "../../core" }
mlua =  { version = "0.8.6", features = ["vendored", "lua54"], optional = true }