[package]
name = "surreal-scripting"
version = "0.1.0"
edition = "2021"

[features]
basic = []
gdscript = []
lua = []

[dependencies]
surreal = { package = "surreal-core", path = "../../core" }
thiserror = "1.0.29"
