[package]
name = "surreal-scripting"
description = "Input engine for Surreal"
authors.workspace = true
edition.workspace = true

[dependencies]
common = { package = "surreal-common", path = "../../common" }
