[package]
name = "surreal-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
surreal = { package = "surreal-core", path = "../core" }
serde = { version = "1.0.152", features = ["derive"] }
clap = { version = "4.0.32", features = ["derive"] }
base64 = "0.21.0"
egui = "0.20.1"
fxhash = "0.2.1"
glob = "0.3.1"
notify = "5.0.0"
thiserror = "1.0.31"
winit = "0.27.5"