[package]
name = "surreal-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
surreal = { package = "surreal-core", path = "../core" }

# core dependencies
serde = { version = "1.0.152", features = ["derive"] }
clap = { version = "4.0.32", features = ["derive"] }
base64 = "0.20.0"
egui = "0.20.1"
fxhash = "0.2.1"
notify = "5.0.0"
thiserror = "1.0.38"

# window management
winit = "0.26.1"
glutin = { version = "0.28.0", default-features = false, features = ["x11"] }