[package]
name = "surreal-scene"
description = "Scene Graph for Surreal"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
surreal = { package = "surreal-core", path = "../../core" }
bitflags = "2.1.0"
