[package]
name = "surreal-scene"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
surreal = { package = "surreal-core", path = "../../core" }
serde = { version = "1.0.159", features = ["derive"] }
thiserror = "1.0.26"
bitflags = "2.1.0"
