[package]
name = "surreal-macros"
authors.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.65"
quote = { version = "1.0" }
syn = { version = "1.0", features = ["full"] }
