[package]
name = "mindustry"
description = "A remake of the classic 'Mindustry' in Rust using Surreal"
version = "0.1.0"
edition = "2021"

[dependencies]
surreal = { version = "*", path = "../..", features = ["desktop"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"