[package]
name = "surreal-macros"
authors.workspace = true
edition.workspace = true
version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.65"
quote = { version = "1.0", default-features = false }
syn = { version = "1.0", features = ["full"] }
