[package]
name = "surreal-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.39"
quote = { version = "1.0", default-features = false }
syn = { version = "1.0", features = ["full"] }
