name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: "builds"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install libasound2-dev libgl1-mesa-dev
        if: matrix.os == 'ubuntu-latest'

      - uses: Swatinem/rust-cache@v1

      - name: Run tests
        run: cargo test --all
