name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: "builds"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    env:
      HEADLESS_ENVIRONMENT: true

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          lfs: true

      - uses: awalsh128/cache-apt-pkgs-action@latest
        if: matrix.os == 'ubuntu-latest'
        with:
          packages: libgl1-mesa-dev libasound2-dev libopenal-dev
          version: 1.0

      - uses: Swatinem/rust-cache@v1
      - run: cargo test --all --all-features
